name: Fix

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  fix:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: latest
      - uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: pnpm
      - run: pnpm install
      - run: pnpm run lint:fix

      - uses: qoomon/actions--create-commit@v1
        id: actions--create-commit
        with:
          message: |
            🎨 pnpm run lint:fix

            [dependabot skip]
          skip-empty: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - if: steps.actions--create-commit.outputs.commit != null
        run: git push
